<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-1SAT413" failures="1" tests="3" name="User john" time="8.551" errors="0" timestamp="2023-12-29T23:11:11 IST">
  <testcase classname="com.automation.selenium_docker.vendorPortalApp.VendorPortalTest" name="loginTest" time="2.011"/>
  <testcase classname="com.automation.selenium_docker.vendorPortalApp.VendorPortalTest" name="dashBoardTest" time="4.045">
    <failure type="java.lang.AssertionError" message="expected [10] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [10] but found [0]
at com.automation.selenium_docker.vendorPortalApp.VendorPortalTest.dashBoardTest(VendorPortalTest.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- dashBoardTest -->
  <testcase classname="com.automation.selenium_docker.vendorPortalApp.VendorPortalTest" name="logoutTest" time="0.009">
    <skipped/>
  </testcase> <!-- logoutTest -->
</testsuite> <!-- User john -->
